os:
  - linux

dist: bionic

language: php

php:
#  - 7.3
#  - 7.4
  - nightly

env:
  - DEPENDENCIES=no
#  - DEPENDENCIES=beta
#  - DEPENDENCIES=low

matrix:
  allow_failures:
    - php: nightly
    - env: DEPENDENCIES=beta
    - env: DEPENDENCIES=low

before_script:
  - if [ "$DEPENDENCIES" = "low" ]; then composer -vvv --prefer-lowest --prefer-stable update; else composer update; fi;

script:
  - mkdir -p build/logs
  - composer validate-files
  - composer check-code-style
  - composer run-tests

after_success:
    - bash <(curl -s https://codecov.io/bash)

before_install:
  - sudo apt-get update
  - sudo apt-get -y install ffmpeg php-imagick libimage-exiftool-perl libmagickwand-dev
  # pecl does not yet support imagick for php8 (= nightly) -> we need to build it from source
  - |
   if [[ $TRAVIS_PHP_VERSION = 'nightly' ]]; then
     git clone https://github.com/Imagick/imagick.git
     cd imagick && phpize && ./configure && make
     echo $(php -i | grep 'extension_dir')
     echo $(php -i | grep 'extension_dir => /home/travis/.phpenv/')
     echo 'Copying imagick.so to ' $(echo $(php -i | grep 'extension_dir => /home') | awk 'NF>1{print $NF}')

     sudo cp modules/imagick.so $(echo $(php -i | grep 'extension_dir => /home/travis/.phpenv/') | awk 'NF>1{print $NF}')
     echo 'Update php.ini file at ' $(echo $(php --ini | grep 'Loaded Configuration File') | awk 'NF>1{print $NF}')
     sudo echo 'extension="imagick.so"' >> $(echo $(php --ini | grep 'Loaded Configuration File') | awk 'NF>1{print $NF}')
     cd ..
   else
     yes | pecl install imagick
   fi
  # Show php modules
  - php -m
  - composer self-update
  # Set composer minimum-stability configuration filter to beta versions
  - if [ "$DEPENDENCIES" = "beta" ]; then perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json; fi;
  # Prevent Travis throwing an out of memory error
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Test if we have a token for github in case the project hits the 60 rph limit
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
